import { Heebo } from 'next/font/google'
import './globals.css'

// Components
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/Footer'


// Theme Provider
import { ThemeProvider } from '@/components/Themes/ThemeProvider'

const heebo = Heebo({ subsets: ['latin'] })

export const metadata = {
  title: 'Portofolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={heebo.className}>
        <ThemeProvider attribute='class' defaultTheme='light'>
        <Navbar/>
        {children}
        <Footer/>
        </ThemeProvider>
        </body>
    </html>
  )
}
